% qpsk_link_robust.m
% QPSK Wireless Communication Link Simulation
%
% This program simulates a QPSK digital communication link over an
% Additive White Gaussian Noise (AWGN) channel. The performance of the
% system is evaluated using Bit Error Rate (BER) and constellation
% diagrams at different noise levels.

clear;
close all;
clc;

%% System Parameters

M = 4;                      % Modulation order for QPSK
k = log2(M);                % Number of bits per symbol
nSym = 2000;                % Number of transmitted QPSK symbols
sps = 8;                    % Samples per symbol
rolloff = 0.25;             % RRC filter roll-off factor
filterSpan = 6;             % RRC filter span in symbols
EbNoVec = 0:6;              % Eb/No range in dB

% Set the random number generator for reproducible results
rng(1);

%% Generate Random Binary Data

bits = randi([0 1], nSym * k, 1);

% Group the bits and convert them into symbol indices
symIdx = bi2de( ...
    reshape(bits, k, []).', ...
    'left-msb');

%% QPSK Modulation

% Map the symbol indices to QPSK symbols using Gray coding
txSymbols = pskmod( ...
    symIdx, ...
    M, ...
    0, ...
    'gray');

%% Root Raised Cosine Pulse-Shaping Filter

% Design a square-root raised cosine filter
rrc = rcosdesign( ...
    rolloff, ...
    filterSpan, ...
    sps, ...
    'sqrt');

%% Transmit Filtering and Oversampling

% Upsample and apply pulse shaping
txSamples = upfirdn( ...
    txSymbols, ...
    rrc, ...
    sps, ...
    1);

% Normalize the transmitted signal to unit average power
txSamples = txSamples / ...
    sqrt(mean(abs(txSamples).^2));

%% Calculate Matched-Filter Delay

% Total transmit and receive filter delay in samples
mfDelay = filterSpan * sps;

% Ensure that the filter delay corresponds to an integer number of symbols
if mod(mfDelay, sps) ~= 0
    error(['Filter delay must be an integer multiple ', ...
           'of the samples per symbol.']);
end

symbolDelay = mfDelay / sps;

%% BER Analysis

ber = zeros(size(EbNoVec));

for ii = 1:length(EbNoVec)

    EbNo = EbNoVec(ii);

    % Configure the AWGN channel
    awgnChan = comm.AWGNChannel( ...
        'EbNo', EbNo, ...
        'BitsPerSymbol', k, ...
        'SamplesPerSymbol', sps, ...
        'SignalPower', mean(abs(txSamples).^2));

    % Pass the transmitted signal through the noisy channel
    rxSamples = awgnChan(txSamples);

    % Apply the matched RRC filter and downsample
    rxMF_all = upfirdn( ...
        rxSamples, ...
        rrc, ...
        1, ...
        sps);

    % Determine the number of valid received symbols
    nRxSymbolsAvailable = ...
        length(rxMF_all) - symbolDelay;

    nCompare = min( ...
        nSym, ...
        nRxSymbolsAvailable);

    % Extract the valid symbol samples after compensating for filter delay
    startIdx = symbolDelay + 1;
    endIdx = symbolDelay + nCompare;

    rxSymbols_down = ...
        rxMF_all(startIdx:endIdx);

    % Display a warning if fewer symbols are available
    if nCompare < nSym
        warning( ...
            'Requested %d symbols but only %d are available.', ...
            nSym, ...
            nCompare);
    end

    %% QPSK Demodulation

    rxSymDetected = pskdemod( ...
        rxSymbols_down, ...
        M, ...
        0, ...
        'gray');

    % Convert the detected symbols back into binary bits
    rxBits = reshape( ...
        de2bi( ...
            rxSymDetected, ...
            k, ...
            'left-msb').', ...
        [], ...
        1);

    % Match the transmitted bit sequence length
    txBitsTrim = bits(1:length(rxBits));

    % Calculate the Bit Error Rate
    ber(ii) = mean(rxBits ~= txBitsTrim);

end

%% Display BER Results

fprintf('\nQPSK BER Simulation Results\n');
fprintf('---------------------------\n');
fprintf('Eb/No (dB)\tBER\n');

for ii = 1:length(EbNoVec)
    fprintf('%d\t\t%.6f\n', ...
        EbNoVec(ii), ...
        ber(ii));
end

%% Plot BER versus Eb/No

figure;

semilogy( ...
    EbNoVec, ...
    ber, ...
    '-o', ...
    'LineWidth', ...
    1.4);

grid on;

xlabel('E_b/N_0 (dB)');
ylabel('Bit Error Rate (BER)');
title('QPSK Communication Link: BER vs. E_b/N_0');

set(gca, 'FontSize', 12);

%% Constellation at Moderate Noise Level

EbNoModerate = 4;

awgnModerate = comm.AWGNChannel( ...
    'EbNo', EbNoModerate, ...
    'BitsPerSymbol', k, ...
    'SamplesPerSymbol', sps, ...
    'SignalPower', mean(abs(txSamples).^2));

% Pass the signal through the AWGN channel
rxModerate = awgnModerate(txSamples);

% Apply matched filtering and downsampling
rxMF_moderate = upfirdn( ...
    rxModerate, ...
    rrc, ...
    1, ...
    sps);

% Determine the number of symbols to display
nPlot = min( ...
    2000, ...
    length(rxMF_moderate) - symbolDelay);

% Extract valid constellation samples
rxConstModerate = rxMF_moderate( ...
    symbolDelay + 1 : ...
    symbolDelay + nPlot);

% Plot the moderate-noise constellation
figure;

plot( ...
    real(rxConstModerate), ...
    imag(rxConstModerate), ...
    '.', ...
    'MarkerSize', ...
    6);

grid on;
axis equal;

xlabel('In-Phase');
ylabel('Quadrature');

title( ...
    sprintf( ...
        'Received QPSK Constellation at E_b/N_0 = %d dB', ...
        EbNoModerate));

%% Low-Noise Constellation

EbNoLowNoise = 20;

awgnLow = comm.AWGNChannel( ...
    'EbNo', EbNoLowNoise, ...
    'BitsPerSymbol', k, ...
    'SamplesPerSymbol', sps, ...
    'SignalPower', mean(abs(txSamples).^2));

% Pass the signal through a low-noise AWGN channel
rxLow = awgnLow(txSamples);

% Apply matched filtering and downsampling
rxMF_low = upfirdn( ...
    rxLow, ...
    rrc, ...
    1, ...
    sps);

% Extract the constellation samples
rxConstLow = rxMF_low( ...
    symbolDelay + 1 : ...
    symbolDelay + nPlot);

% Plot the low-noise constellation
figure;

plot( ...
    real(rxConstLow), ...
    imag(rxConstLow), ...
    'o', ...
    'MarkerSize', ...
    5);

grid on;
axis equal;

xlabel('In-Phase');
ylabel('Quadrature');

title( ...
    'QPSK Constellation - Low Noise (Clean and Tight)');

%% High-Noise Constellation

EbNoHighNoise = 0;

awgnHigh = comm.AWGNChannel( ...
    'EbNo', EbNoHighNoise, ...
    'BitsPerSymbol', k, ...
    'SamplesPerSymbol', sps, ...
    'SignalPower', mean(abs(txSamples).^2));

% Pass the signal through a high-noise AWGN channel
rxHigh = awgnHigh(txSamples);

% Apply matched filtering and downsampling
rxMF_high = upfirdn( ...
    rxHigh, ...
    rrc, ...
    1, ...
    sps);

% Extract the constellation samples
rxConstHigh = rxMF_high( ...
    symbolDelay + 1 : ...
    symbolDelay + nPlot);

% Plot the high-noise constellation
figure;

plot( ...
    real(rxConstHigh), ...
    imag(rxConstHigh), ...
    '.', ...
    'MarkerSize', ...
    6);

grid on;
axis equal;

xlabel('In-Phase');
ylabel('Quadrature');

title( ...
    'QPSK Constellation - High Noise (Messy and Spread)');

%% End of Simulation

disp('QPSK communication link simulation completed successfully.');
